### PR TITLE
docs: invoice returns

### PR DESCRIPTION
**Pull request by akshayitzme**
- [x] Docs: Invoice Returns

### CODE REVIEW

**Comment by 18alantom** [comment]
Seems fine, only noticeable issue is the screenshots under
- Purchase Invoice Return impact on General Ledger
- Sales Invoice Return impact on General Ledger

There's a double left border cause of the screenshot width

Screenshot 2023-11-22 at 11 36 56

**Comment by 18alantom** [comment]
@akshayitzme screenshot distance from the edges is uneven for both the updated images:

Screenshot 2023-11-22 at 12 28 02

**Comment by akshayitzme** [comment]
> @akshayitzme screenshot distance from the edges is uneven for both the updated images:
> 
> Screenshot 2023-11-22 at 12 28 02

Corrected. Please check now

**Comment by akshayitzme** [comment]
@18alantom Reminder

**Pull request merged**
